variable "project_name" {}
variable "region" {}
variable "instance_tenancy" {}
variable "vpc_cidr_block" {}
variable "enable_dns_hostnames" {}
variable "enable_dns_support" {}
variable "pubsub_cidrs" {}
variable "ptesub_cidrs" {}
variable "inbound_ports" {}
variable "outbound_ports" {}
variable "username" {}
variable "instance_class" {}
variable "instance_type" {}
variable "identifier" {}
variable "ami" {}
variable "engine_version" {}
variable "allocated_storage" {}
variable "storage_type" {}
variable "domain_name" {}
variable "alternative_name" {}
variable "nat_gateway_route_cidr" {}
variable "key_name" {}
variable "container_name" {}
variable "containerPort" {}
variable "hostPort" {}
variable "load_balancer_type" {}
variable "target_type" {}
variable "skip_final_snapshot" {}
variable "engine" {}
variable "password" {}
variable "cluster_name" {}
variable "publicly_accessible" {}
variable "records" {}
variable "validation_method" {}
variable "private_zone" {}
variable "network_mode" {}
variable "aws_ecs_task_definition" {}
variable "protocol" {}
variable "listener_port" {}